### ISSUE TITLE
History can be restored successfully while bookmarks, categories, and favorites returns an error

### ISSUE THREAD

**Issue by infyProductions** [PhantomShift/nekotatsu#3] opened 2024-04-12 01:34 UTC
I was testing this app to try restoring my Neko converted backup (which is restored from Mihon) to a Kotatsu compatible backup file. 

It seems that "History" can be restored without any errors (see figure 1):
![Screenshot 2024-04-12 090702](https://github.com/PhantomShift/nekotatsu/assets/31158494/a4fdb8e2-97e1-4920-9151-6ec716485aac)
_[figure 1: History restoration returns success]_
However, with "Bookmarks", "Categories" and "Favorites" seems to fail with an error: `Value null at persent type org.JSONObject$1 cannot be converted to double` (see figure 2):
![Screenshot 2024-04-12 084736](https://github.com/PhantomShift/nekotatsu/assets/31158494/fcea6d77-7c16-4758-98d1-51d7eebd2cab)
_[figure 2: An attempt to restore Bookmarks, Categories, and Favorites returns an error]_

Platform: Windows (Windows 11 23H2)
Nekotatsu release: nekotatsu-v1.1.0-Windows-x86_64
Kotatsu version: 6.8.3
Device/emulator used for Kotatsu: WSA version 2311.40000.5.0

Note:
I even went as far as performing `nekotatsu clear` and `nekotatsu update` just to have a clean and updated slate.

**Comment by PhantomShift** [comment] 2024-04-12 02:24
Should be fixed in [latest release](https://github.com/PhantomShift/nekotatsu/releases/tag/v1.1.1) with this commit in particular https://github.com/PhantomShift/nekotatsu/commit/4776f4ed4b87ecfb661e236d4e9b711eab0158e3, feel free to re-open if the issue persists

**Closed as completed by PhantomShift** 2024-04-12 02:24 UTC

**Comment by infyProductions** [comment] 2024-04-12 03:18
Update: the full restore was completed successfully. Thank you for the quick update release.
![image](https://github.com/PhantomShift/nekotatsu/assets/31158494/1529cd4b-e0df-4283-9de3-eac3eab1f803)

**Comment by infyProductions** [comment] 2024-05-17 03:11
Hello again. I've updated Kotatsu to the latest version (7.0.1) and it fails to restore again with the invalid backup. The backup is made with the latest version of the tool (1.1.1). I tried clearing and updating the source and parser info beforehand but to no avail.

P.S.: The 1.1.1 version returns "nekotatsu 1.0.0" when running `.\nekotatsu.exe -V`

**Comment by PhantomShift** [comment] 2024-05-17 03:37
Hey, appreciate the report, but unless it's the exact same error, it'd be helpful if you create a brand new issue with all the relevant details for organization and clarity.

It's rather late for me right now so I'll start investigating tomorrow. Cheers.

**Comment by infyProductions** [comment] 2024-05-17 07:04
Okay, I'll file the issue tomorrow since I had work at the moment

**Comment by PhantomShift** [comment] 2024-05-17 17:10
I went ahead and filed it myself since I've investigated and found the cause of the issue, once again appreciate the report!
https://github.com/PhantomShift/nekotatsu/issues/4
